[pytest]
asyncio_mode = auto

testpaths = tests


pythonpath = .

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -ra
    --strict-markers

markers =
    debug: system & configuration tests
    database: database/repository tests
    services: service layer tests
    controllers: api tests